[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SDP-miRNA"
version = "0.0.1"
description = "Inference of miRNA behaviour using SDP approaches"
licence = {file = "LICENSE"}
readme = "README.md"

authors = [
  { name="William Hilton", email="williamjgh2000@gmail.com" },
]

keywords = ["scRNA-seq", "inference", "optimization", "semidefinite-programming"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "sympy",
    "matplotlib",
    "gurobipy>=12.0.1",
    "mosek==11.2.2",
    "pandas",
    "tqdm",
    "seaborn",
    "Jinja2"
]

[project.optional-dependencies]

[project.urls]
Repository = "https://github.com/willjgh/SDP-miRNA"